services:
  oci-helper:
    image: ghcr.io/viogus/oci-helper:latest
    container_name: oci-helper
    restart: unless-stopped
    ports:
      - "8818:8818"
    volumes:
      - ./application.yml:/app/oci-helper/application.yml
      - ./oci-helper.db:/app/oci-helper/oci-helper.db
      - ./keys:/app/oci-helper/keys
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  websockify:
    image: ghcr.io/yohann0617/oci-helper-websockify:master
    container_name: oci-helper-ws
    restart: unless-stopped
    ports:
      - "6080:6080"
